import hashlib
import io
import json
import logging
import uuid
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.models.models import (
    Antibody,
    AuditLog,
    CocktailLot,
    CocktailLotDocument,
    CocktailLotSource,
    CocktailRecipe,
    CocktailRecipeComponent,
    Fluorochrome,
    Lab,
    Lot,
    LotDocument,
    LotRequest,
    QCStatus,
    ReagentComponent,
    StorageCell,
    StorageUnit,
    SupportTicket,
    TicketReply,
    User,
    Vial,
)
from app.services.audit import (
    snapshot_antibody,
    snapshot_fluorochrome,
    snapshot_lot,
    snapshot_vial,
)
from app.services.object_storage import object_storage

logger = logging.getLogger(__name__)


def _make_sample_pdf(title: str) -> bytes:
    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 40, "SAMPLE QC DOCUMENT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, title, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "This is demo data generated by LabAid.", align="C")
    return pdf.output()


def _upload_demo_doc(lab_id, lot, user_id, db, filename, title, ts, _audit):
    doc_id = uuid.uuid4()
    pdf_bytes = _make_sample_pdf(title)
    checksum = hashlib.sha256(pdf_bytes).hexdigest()
    file_path = f"{lab_id}/{lot.id}/{doc_id}_{filename}"

    if object_storage.enabled:
        try:
            object_storage.upload(
                file_path,
                io.BytesIO(pdf_bytes),
                content_type="application/pdf",
                tags={"storage-class": "hot", "lab-active": "true"},
            )
        except Exception:
            logger.error("Failed to upload demo QC doc: %s", file_path)

    doc = LotDocument(
        id=doc_id,
        lot_id=lot.id,
        lab_id=lab_id,
        user_id=user_id,
        file_path=file_path,
        file_name=filename,
        file_size=len(pdf_bytes),
        content_type="application/pdf",
        checksum_sha256=checksum,
        description=f"QC verification for {lot.lot_number}",
        is_qc_document=True,
        created_at=ts,
    )
    db.add(doc)
    db.flush()

    _audit(
        "document.uploaded", "lot", lot.id, ts,
        after_state=json.dumps({
            "document_id": str(doc.id),
            "file_name": filename,
            "description": doc.description,
            "is_qc_document": True,
        }),
        note=f"Uploaded: {filename} — {doc.description}",
    )
    return doc


def wipe_demo_lab(db: Session, lab: Lab) -> None:
    assert lab.is_demo, "wipe_demo_lab called on non-demo lab"
    lab_id = lab.id

    # 1. Remove cell references from vials
    db.execute(
        text("UPDATE vials SET location_cell_id = NULL WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 2. Remove cell references from cocktail lots
    db.execute(
        text("UPDATE cocktail_lots SET location_cell_id = NULL WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 3. Ticket replies (via ticket IDs)
    db.execute(
        text(
            "DELETE FROM ticket_replies WHERE ticket_id IN "
            "(SELECT id FROM support_tickets WHERE lab_id = :id)"
        ),
        {"id": str(lab_id)},
    )

    # 4. Support tickets
    db.execute(
        text("DELETE FROM support_tickets WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 5. Lot requests
    db.execute(
        text("DELETE FROM lot_requests WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 6. Object storage blobs for lot documents
    docs = (
        db.query(LotDocument)
        .filter(LotDocument.lab_id == lab_id)
        .all()
    )
    if object_storage.enabled:
        for doc in docs:
            try:
                object_storage.delete(doc.file_path)
            except Exception:
                logger.error("Failed to delete demo blob: %s", doc.file_path)

    # 7. Lot documents
    db.execute(
        text("DELETE FROM lot_documents WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 8. Object storage blobs for cocktail lot documents
    cocktail_docs = (
        db.query(CocktailLotDocument)
        .filter(CocktailLotDocument.lab_id == lab_id)
        .all()
    )
    if object_storage.enabled:
        for doc in cocktail_docs:
            try:
                object_storage.delete(doc.file_path)
            except Exception:
                logger.error("Failed to delete demo blob: %s", doc.file_path)

    # 9. Cocktail lot documents
    db.execute(
        text("DELETE FROM cocktail_lot_documents WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 10. Cocktail lot sources (via cocktail_lot IDs)
    db.execute(
        text(
            "DELETE FROM cocktail_lot_sources WHERE cocktail_lot_id IN "
            "(SELECT id FROM cocktail_lots WHERE lab_id = :id)"
        ),
        {"id": str(lab_id)},
    )

    # 11. Cocktail lots
    db.execute(
        text("DELETE FROM cocktail_lots WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 12. Cocktail recipe components (via recipe IDs)
    db.execute(
        text(
            "DELETE FROM cocktail_recipe_components WHERE recipe_id IN "
            "(SELECT id FROM cocktail_recipes WHERE lab_id = :id)"
        ),
        {"id": str(lab_id)},
    )

    # 13. Cocktail recipes
    db.execute(
        text("DELETE FROM cocktail_recipes WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 14. Vials
    db.execute(
        text("DELETE FROM vials WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 15. Lots
    db.execute(
        text("DELETE FROM lots WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 16. Reagent components (via antibody IDs)
    db.execute(
        text(
            "DELETE FROM reagent_components WHERE antibody_id IN "
            "(SELECT id FROM antibodies WHERE lab_id = :id)"
        ),
        {"id": str(lab_id)},
    )

    # 17. Antibodies
    db.execute(
        text("DELETE FROM antibodies WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 18. Fluorochromes
    db.execute(
        text("DELETE FROM fluorochromes WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 19. Storage cells (via storage unit IDs)
    db.execute(
        text(
            "DELETE FROM storage_cells WHERE storage_unit_id IN "
            "(SELECT id FROM storage_units WHERE lab_id = :id)"
        ),
        {"id": str(lab_id)},
    )

    # 20. Storage units
    db.execute(
        text("DELETE FROM storage_units WHERE lab_id = :id"),
        {"id": str(lab_id)},
    )

    # 21. Audit logs via SECURITY DEFINER function
    db.execute(
        text("SELECT wipe_demo_audit_logs(:lab_id)"),
        {"lab_id": str(lab_id)},
    )

    # 22. Delete extra users (keep the demo admin)
    db.execute(
        text(
            "DELETE FROM users WHERE lab_id = :id "
            "AND email NOT LIKE 'demo-%@demo.labaid.io'"
        ),
        {"id": str(lab_id)},
    )

    # 23. Reset the demo admin user
    demo_user = (
        db.query(User)
        .filter(User.lab_id == lab_id, User.email.like("demo-%@demo.labaid.io"))
        .first()
    )
    if demo_user:
        demo_user.is_active = False
        demo_user.invite_token = None
        demo_user.invite_token_expires_at = None

    # 24. Update lab metadata
    lab.demo_reset_at = datetime.now(timezone.utc)
    lab.demo_cycle_count = (lab.demo_cycle_count or 0) + 1

    db.flush()


def seed_demo_lab(db: Session, lab: Lab, demo_user: User) -> None:
    assert lab.is_demo, "seed_demo_lab called on non-demo lab"
    lab_id = lab.id
    user_id = demo_user.id
    now = datetime.now(timezone.utc)

    # ── Reference dates ──
    # History spans ~2 years. Anchor everything relative to `now`.
    origin = now - timedelta(days=730)  # ~2 years ago

    def _work_hour(dt):
        return dt.replace(hour=9 + (hash(str(dt)) % 8), minute=(hash(str(dt)) >> 4) % 60)

    def _audit(action, entity_type, entity_id, ts, **kwargs):
        entry = AuditLog(
            lab_id=lab_id, user_id=user_id,
            action=action, entity_type=entity_type, entity_id=entity_id,
            created_at=ts, **kwargs,
        )
        db.add(entry)

    # ── Antibody definitions with 6 lots each ──
    ANTIBODIES = [
        {
            "target": "CD45", "fluorochrome": "FITC", "fluoro_color": "#3cb44b",
            "clone": "HI30", "vendor": "Sysmex", "catalog_number": "21-F45-100",
            "stability_days": 90, "low_stock_threshold": 3, "approved_low_threshold": 2,
            "created_offset_days": 0,
            "lots": [
                {"lot_number": "SX24-02891", "vial_count": 5, "interval_days": 26, "lot_offset_days": 2},
                {"lot_number": "SX24-07453", "vial_count": 5, "interval_days": 26, "lot_offset_days": None},
                {"lot_number": "SX24-11456", "vial_count": 5, "interval_days": 26, "lot_offset_days": None},
                {"lot_number": "SX25-03812", "vial_count": 5, "interval_days": 26, "lot_offset_days": None},
                {"lot_number": "SX25-08233", "vial_count": 5, "interval_days": 26, "lot_offset_days": None},
                {"lot_number": "SX25-12044", "vial_count": 5, "interval_days": 26, "lot_offset_days": None},
                {"lot_number": "SX26-01877", "vial_count": 5, "interval_days": 26, "lot_offset_days": None, "pending_qc": True},
            ],
        },
        {
            "target": "CD3", "fluorochrome": "PE", "fluoro_color": "#e6194b",
            "clone": "UCHT1", "vendor": "Sysmex", "catalog_number": "21-PE3-050",
            "stability_days": 60, "low_stock_threshold": 2, "approved_low_threshold": 1,
            "created_offset_days": 14,
            "lots": [
                {"lot_number": "SX24-04112", "vial_count": 4, "interval_days": 32, "lot_offset_days": 16},
                {"lot_number": "SX24-08890", "vial_count": 4, "interval_days": 32, "lot_offset_days": None},
                {"lot_number": "SX25-01234", "vial_count": 4, "interval_days": 32, "lot_offset_days": None},
                {"lot_number": "SX25-05678", "vial_count": 4, "interval_days": 32, "lot_offset_days": None},
                {"lot_number": "SX25-09012", "vial_count": 4, "interval_days": 32, "lot_offset_days": None},
                {"lot_number": "SX25-12456", "vial_count": 2, "interval_days": 32, "lot_offset_days": None},
            ],
        },
    ]

    # ── Lab settings (origin) ──
    _audit(
        "lab.settings_updated", "lab", lab_id,
        _work_hour(origin),
        after_state=json.dumps({"storage_enabled": True}),
        note="Enabled storage feature",
    )

    # ── Fluorochromes ──
    fluoro_map = {}
    for i, ab_cfg in enumerate(ANTIBODIES):
        fname = ab_cfg["fluorochrome"]
        if fname in fluoro_map:
            continue
        f = Fluorochrome(lab_id=lab_id, name=fname, color=ab_cfg["fluoro_color"])
        db.add(f)
        db.flush()
        fluoro_map[fname] = f
        _audit(
            "fluorochrome.created", "fluorochrome", f.id,
            _work_hour(origin + timedelta(hours=i)),
            after_state=json.dumps(snapshot_fluorochrome(f)),
        )
    # Also add APC (not used by any antibody yet, but available)
    if "APC" not in fluoro_map:
        f = Fluorochrome(lab_id=lab_id, name="APC", color="#4363d8")
        db.add(f)
        db.flush()
        fluoro_map["APC"] = f
        _audit(
            "fluorochrome.created", "fluorochrome", f.id,
            _work_hour(origin + timedelta(hours=2)),
            after_state=json.dumps(snapshot_fluorochrome(f)),
        )

    # ── Storage unit: Reagent Fridge 4×4 ──
    fridge = StorageUnit(
        lab_id=lab_id, name="Reagent Fridge (4°C)",
        rows=4, cols=4, temperature="4°C",
    )
    db.add(fridge)
    db.flush()

    cells = []
    for r in range(4):
        for c in range(4):
            cell = StorageCell(
                storage_unit_id=fridge.id, row=r, col=c,
                label=f"{chr(65 + r)}{c + 1}",
            )
            db.add(cell)
            cells.append(cell)
    db.flush()

    _audit(
        "storage_unit.created", "storage_unit", fridge.id,
        _work_hour(origin + timedelta(days=1)),
        after_state=json.dumps({"name": fridge.name, "rows": 4, "cols": 4}),
    )

    # ── Temporary storage ──
    temp = StorageUnit(
        lab_id=lab_id, name="Temporary Storage",
        rows=1, cols=1, temperature=None, is_temporary=True,
    )
    db.add(temp)
    db.flush()
    temp_cell = StorageCell(storage_unit_id=temp.id, row=0, col=0, label="A1")
    db.add(temp_cell)
    db.flush()

    # Track which fridge cells are currently occupied (for realistic placement)
    free_cells = list(cells)  # mutable copy

    def _allocate_cells(n):
        allocated = free_cells[:n]
        del free_cells[:n]
        return allocated

    def _free_cell(cell):
        free_cells.append(cell)

    # ── Process each antibody ──
    for ab_cfg in ANTIBODIES:
        ab_created = _work_hour(origin + timedelta(days=ab_cfg["created_offset_days"]))

        ab = Antibody(
            lab_id=lab_id,
            target=ab_cfg["target"], fluorochrome=ab_cfg["fluorochrome"],
            clone=ab_cfg["clone"], vendor=ab_cfg["vendor"],
            catalog_number=ab_cfg["catalog_number"],
            stability_days=ab_cfg["stability_days"],
            low_stock_threshold=ab_cfg["low_stock_threshold"],
            approved_low_threshold=ab_cfg["approved_low_threshold"],
            target_normalized=ab_cfg["target"].upper().replace("-", "").replace(" ", ""),
            fluorochrome_normalized=ab_cfg["fluorochrome"].upper().replace("-", "").replace(" ", ""),
        )
        db.add(ab)
        db.flush()

        _audit(
            "antibody.created", "antibody", ab.id, ab_created,
            after_state=json.dumps(snapshot_antibody(ab)),
        )

        # ── Chain lots with FEFO ──
        prev_lot_last_depleted = None
        lot_cursor = ab_created + timedelta(days=ab_cfg["lots"][0]["lot_offset_days"])

        for lot_idx, lot_cfg in enumerate(ab_cfg["lots"]):
            is_last_lot = lot_idx == len(ab_cfg["lots"]) - 1
            vial_count = lot_cfg["vial_count"]
            interval = lot_cfg["interval_days"]
            is_pending_qc = lot_cfg.get("pending_qc", False)

            # Lot creation time
            if is_pending_qc:
                # Pending QC lot: received 2 days ago, awaiting approval
                lot_created = _work_hour(now - timedelta(days=2))
            elif lot_cfg["lot_offset_days"] is not None:
                lot_created = _work_hour(origin + timedelta(days=ab_cfg["created_offset_days"] + lot_cfg["lot_offset_days"]))
            else:
                # Auto-schedule: new lot arrives when previous lot has ~2 vials left
                lot_created = _work_hour(lot_cursor)

            # Expiration: 8-12 months from creation
            exp_date = (lot_created + timedelta(days=300)).date()

            if is_pending_qc:
                lot = Lot(
                    antibody_id=ab.id, lab_id=lab_id,
                    lot_number=lot_cfg["lot_number"],
                    expiration_date=exp_date,
                    qc_status=QCStatus.PENDING,
                    created_at=lot_created,
                )
                db.add(lot)
                db.flush()

                _audit("lot.created", "lot", lot.id, lot_created,
                       after_state=json.dumps(snapshot_lot(lot)))

                # All vials sealed, in storage
                vial_objs = []
                for vi in range(vial_count):
                    cell_id = None
                    if free_cells:
                        cell_id = free_cells.pop(0).id
                    v = Vial(
                        lot_id=lot.id, lab_id=lab_id,
                        status="sealed",
                        location_cell_id=cell_id,
                        received_at=lot_created,
                    )
                    db.add(v)
                    vial_objs.append(v)
                db.flush()

                _audit(
                    "vial.received", "lot", lot.id,
                    lot_created + timedelta(minutes=10),
                    after_state=json.dumps({
                        "lot_number": lot.lot_number,
                        "antibody_target": ab.target,
                        "antibody_fluorochrome": ab.fluorochrome,
                        "quantity": vial_count,
                        "vial_ids": [str(v.id) for v in vial_objs],
                    }),
                    note=f"Received {vial_count} vials → Reagent Fridge (4°C)",
                )
                continue

            # QC doc uploaded 1 day after lot created, approved same day
            qc_doc_time = _work_hour(lot_created + timedelta(days=1))
            qc_approved_time = _work_hour(lot_created + timedelta(days=1, hours=3))

            lot = Lot(
                antibody_id=ab.id, lab_id=lab_id,
                lot_number=lot_cfg["lot_number"],
                expiration_date=exp_date,
                qc_status=QCStatus.APPROVED,
                qc_approved_by=user_id,
                qc_approved_at=qc_approved_time,
                created_at=lot_created,
            )
            db.add(lot)
            db.flush()

            _audit("lot.created", "lot", lot.id, lot_created,
                   after_state=json.dumps(snapshot_lot(lot)))

            # ── Generate vial timeline ──
            # First use: after QC approval, or after previous lot depleted (FEFO)
            first_use = qc_approved_time + timedelta(hours=2)
            if prev_lot_last_depleted and prev_lot_last_depleted > first_use:
                first_use = prev_lot_last_depleted + timedelta(days=1)

            vial_schedule = []
            cursor = first_use
            for vi in range(vial_count):
                open_time = _work_hour(cursor)
                deplete_time = _work_hour(open_time + timedelta(days=interval))
                stab_exp = (open_time.date() + timedelta(days=ab_cfg["stability_days"]))
                open_exp = min(stab_exp, exp_date)

                if open_time >= now:
                    # Future: stays sealed
                    vial_schedule.append({"status": "sealed", "opened_at": None,
                                          "depleted_at": None, "open_expiration": None})
                elif deplete_time >= now:
                    # Currently in use
                    vial_schedule.append({"status": "opened", "opened_at": open_time,
                                          "depleted_at": None, "open_expiration": open_exp})
                else:
                    vial_schedule.append({"status": "depleted", "opened_at": open_time,
                                          "depleted_at": deplete_time, "open_expiration": open_exp})

                cursor = deplete_time + timedelta(days=1)

            # ── Create vials ──
            vial_objs = []
            sealed_cells = []
            for vi, vs in enumerate(vial_schedule):
                cell_id = None
                if vs["status"] == "sealed" and free_cells:
                    c = free_cells[0]
                    cell_id = c.id
                    sealed_cells.append(c)
                    # Don't remove from free_cells yet — we'll manage below

                v = Vial(
                    lot_id=lot.id, lab_id=lab_id,
                    status=vs["status"],
                    location_cell_id=cell_id,
                    received_at=lot_created,
                    opened_at=vs["opened_at"],
                    opened_by=user_id if vs["opened_at"] else None,
                    open_expiration=vs["open_expiration"],
                    depleted_at=vs["depleted_at"],
                    depleted_by=user_id if vs["depleted_at"] else None,
                )
                db.add(v)
                vial_objs.append(v)

                # Allocate cell only for sealed vials
                if vs["status"] == "sealed" and free_cells:
                    free_cells.pop(0)

            db.flush()

            # Audit: vial.received
            _audit(
                "vial.received", "lot", lot.id,
                lot_created + timedelta(minutes=10),
                after_state=json.dumps({
                    "lot_number": lot.lot_number,
                    "antibody_target": ab.target,
                    "antibody_fluorochrome": ab.fluorochrome,
                    "quantity": vial_count,
                    "vial_ids": [str(v.id) for v in vial_objs],
                }),
                note=f"Received {vial_count} vials → Reagent Fridge (4°C)",
            )

            # Audit: QC doc uploaded
            _upload_demo_doc(
                lab_id, lot, user_id, db,
                filename=f"QC_{lot_cfg['lot_number']}.pdf",
                title=f"QC Report - {lot_cfg['lot_number']}",
                ts=qc_doc_time,
                _audit=_audit,
            )

            # Audit: QC approved
            _audit("lot.qc_approved", "lot", lot.id, qc_approved_time,
                   before_state=json.dumps({"qc_status": "pending"}),
                   after_state=json.dumps(snapshot_lot(lot)))

            # ── Audit: individual vial opens and depletes ──
            for vi, vs in enumerate(vial_schedule):
                v = vial_objs[vi]
                if vs["opened_at"]:
                    _audit(
                        "vial.opened", "vial", v.id, vs["opened_at"],
                        before_state=json.dumps({
                            "id": str(v.id), "lot_id": str(lot.id), "status": "sealed",
                        }),
                        after_state=json.dumps({
                            "id": str(v.id), "lot_id": str(lot.id), "status": "opened",
                            "opened_at": str(vs["opened_at"]),
                        }),
                    )
                if vs["depleted_at"]:
                    _audit(
                        "vial.depleted", "vial", v.id, vs["depleted_at"],
                        before_state=json.dumps({
                            "id": str(v.id), "lot_id": str(lot.id), "status": "opened",
                        }),
                        after_state=json.dumps({
                            "id": str(v.id), "lot_id": str(lot.id), "status": "depleted",
                            "depleted_at": str(vs["depleted_at"]),
                        }),
                    )

            # Track last depletion for FEFO chaining
            depleted_times = [vs["depleted_at"] for vs in vial_schedule if vs["depleted_at"]]
            prev_lot_last_depleted = max(depleted_times) if depleted_times else None

            # Schedule next lot arrival: when ~2 sealed vials remain
            sealed_count = sum(1 for vs in vial_schedule if vs["status"] == "sealed")
            if sealed_count == 0 and depleted_times:
                # All used up — next lot should have arrived earlier
                # Back-calculate: arrive when 2 vials were still sealed
                back_offset = interval * 2
                lot_cursor = max(depleted_times) - timedelta(days=back_offset)
            else:
                lot_cursor = cursor - timedelta(days=interval * 2)

            # ── Archive fully-depleted lots ──
            all_depleted = all(vs["status"] == "depleted" for vs in vial_schedule)
            if all_depleted and not is_last_lot:
                archive_time = _work_hour(max(depleted_times) + timedelta(days=2))
                if archive_time < now:
                    lot.is_archived = True
                    lot.archive_note = "All vials depleted"
                    _audit(
                        "lot.archived", "lot", lot.id, archive_time,
                        before_state=json.dumps({"is_archived": False}),
                        after_state=json.dumps(snapshot_lot(lot)),
                        note="All vials depleted",
                    )

    db.flush()
