"""PDF rendering for compliance reports using fpdf2."""

from datetime import datetime, timezone

from fpdf import FPDF


class LabAidPDF(FPDF):
    """Base PDF class with branded header and footer."""

    def __init__(self, title: str, lab_name: str, pulled_by: str = ""):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.report_title = title
        self.lab_name = lab_name
        self.pulled_by = pulled_by
        self.generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 8, self.report_title, new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        parts = [f"Lab: {self.lab_name}"]
        if self.pulled_by:
            parts.append(f"Pulled by: {self.pulled_by}")
        parts.append(f"Generated: {self.generated_at}")
        self.cell(0, 5, "  |  ".join(parts), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  —  Electronically generated by LabAid. Do not alter.", align="C")

    def _table_header(self, columns: list[tuple[str, int]]):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(240, 240, 245)
        for col_name, col_width in columns:
            self.cell(col_width, 7, col_name, border=1, fill=True)
        self.ln()

    def _table_row(self, values: list[str], widths: list[int]):
        self.set_font("Helvetica", "", 7)
        max_h = 7
        line_heights = []
        for val, w in zip(values, widths):
            text_w = self.get_string_width(val)
            lines = max(1, int(text_w / (w - 2)) + 1)
            line_heights.append(lines * 4)
        row_h = max(max_h, max(line_heights))

        if self.get_y() + row_h > self.h - 20:
            self.add_page()

        y_start = self.get_y()
        x_start = self.get_x()
        for i, (val, w) in enumerate(zip(values, widths)):
            x = x_start + sum(widths[:i])
            self.set_xy(x, y_start)
            self.multi_cell(w, 4, val, border=1, new_x="RIGHT", new_y="TOP", max_line_height=row_h)
        self.set_y(y_start + row_h)


def _render_table(title: str, lab_name: str, pulled_by: str,
                  columns: list[tuple[str, int]], data: list[dict],
                  row_fn) -> bytes:
    """Shared helper to render a flat table PDF."""
    pdf = LabAidPDF(title, lab_name, pulled_by)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf._table_header(columns)
    widths = [c[1] for c in columns]
    for row in data:
        pdf._table_row(row_fn(row), widths)
    return pdf.output()


def render_lot_activity_pdf(data: list[dict], lab_name: str, pulled_by: str = "") -> bytes:
    columns = [
        ("Lot #", 30), ("Expiration", 24), ("Received", 24), ("Received By", 35),
        ("QC Doc", 16), ("QC Approved", 24), ("QC Approved By", 35),
        ("First Opened", 24), ("Last Opened", 24),
    ]
    return _render_table(
        "Lot Activity Report", lab_name, pulled_by, columns, data,
        lambda r: [
            r["lot_number"], r["expiration"], r["received"], r["received_by"],
            r["qc_doc"], r["qc_approved"], r["qc_approved_by"],
            r["first_opened"], r["last_opened"],
        ],
    )


def render_usage_pdf(data: list[dict], lab_name: str, pulled_by: str = "") -> bytes:
    columns = [
        ("Lot #", 30), ("Expiration", 22), ("Received", 22),
        ("Vials Received", 25), ("Vials Consumed", 25),
        ("First Opened", 24), ("Last Opened", 24),
        ("Avg/Week", 20), ("Status", 22),
    ]
    return _render_table(
        "Usage Report", lab_name, pulled_by, columns, data,
        lambda r: [
            r["lot_number"], r["expiration"], r["received"],
            str(r["vials_received"]), str(r["vials_consumed"]),
            r["first_opened"], r["last_opened"],
            r["avg_week"], r["status"],
        ],
    )


def render_admin_activity_pdf(data: list[dict], lab_name: str, pulled_by: str = "") -> bytes:
    columns = [
        ("Timestamp", 42), ("Action", 40), ("Performed By", 40),
        ("Target", 60), ("Details", 75),
    ]
    return _render_table(
        "Admin Activity Report", lab_name, pulled_by, columns, data,
        lambda r: [
            r["timestamp"][:19], r["action"], r["performed_by"],
            r["target"], r["details"],
        ],
    )


def render_audit_trail_pdf(data: list[dict], lab_name: str, pulled_by: str = "") -> bytes:
    columns = [
        ("Timestamp", 42), ("User", 35), ("Action", 35),
        ("Entity Type", 25), ("Entity", 70), ("Note", 55), ("Support", 15),
    ]
    return _render_table(
        "Audit Trail Report", lab_name, pulled_by, columns, data,
        lambda r: [
            r["timestamp"][:19], r["user"], r["action"],
            r["entity_type"], r["entity"], r["note"], r["support"],
        ],
    )
