"""add description to lot_documents

Revision ID: 0614846ef696
Revises: 296cbfbabe33
Create Date: 2026-02-02 17:57:04.230773
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0614846ef696'
down_revision: Union[str, None] = '296cbfbabe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot_documents', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot_documents', 'description')
    # ### end Alembic commands ###
