"""remove is_testing from antibodies

Revision ID: 0d80919ceaa8
Revises: a5aa756ec411
Create Date: 2026-02-02 02:35:51.685186
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d80919ceaa8'
down_revision: Union[str, None] = 'a5aa756ec411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('antibodies', 'is_testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('antibodies', sa.Column('is_testing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
