"""add is_qc_document to lot_documents

Revision ID: 1ef45561a6a5
Revises: 0614846ef696
Create Date: 2026-02-02 23:22:29.796745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef45561a6a5'
down_revision: Union[str, None] = '0614846ef696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot_documents', sa.Column('is_qc_document', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot_documents', 'is_qc_document')
    # ### end Alembic commands ###
