"""add archive_note to lots

Revision ID: 296cbfbabe33
Revises: 6a1bc82a9f12
Create Date: 2026-02-02 17:34:48.396064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296cbfbabe33'
down_revision: Union[str, None] = '6a1bc82a9f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('archive_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'archive_note')
    # ### end Alembic commands ###
