"""add_stability_days_and_open_expiration

Revision ID: 675445aab6eb
Revises: faaf1700fa72
Create Date: 2026-02-01 02:32:39.840182
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675445aab6eb'
down_revision: Union[str, None] = 'faaf1700fa72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('antibodies', sa.Column('stability_days', sa.Integer(), nullable=True))
    op.add_column('vials', sa.Column('open_expiration', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vials', 'open_expiration')
    op.drop_column('antibodies', 'stability_days')
    # ### end Alembic commands ###
