"""add gs1_ai jsonb column to lots

Revision ID: 6a1bc82a9f12
Revises: 0d80919ceaa8
Create Date: 2026-02-02 07:20:57.139483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1bc82a9f12'
down_revision: Union[str, None] = '0d80919ceaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('gs1_ai', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'gs1_ai')
    # ### end Alembic commands ###
