"""add low stock threshold to antibody

Revision ID: 6faa2cf97081
Revises: 337ca561def2
Create Date: 2026-02-01 02:57:45.920820
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faa2cf97081'
down_revision: Union[str, None] = '337ca561def2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('antibodies', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('antibodies', 'low_stock_threshold')
    # ### end Alembic commands ###
