"""add_stripe_billing

Revision ID: ca82dc356b68
Revises: s3b4c5d6e7f8
Create Date: 2026-02-27 02:58:28.419521
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca82dc356b68'
down_revision: Union[str, None] = 's3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_stripe_event_id'), 'stripe_events', ['stripe_event_id'], unique=True)
    op.add_column('labs', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('labs', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('labs', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'labs', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labs', type_='unique')
    op.drop_column('labs', 'billing_email')
    op.drop_column('labs', 'stripe_subscription_id')
    op.drop_column('labs', 'stripe_customer_id')
    op.drop_index(op.f('ix_stripe_events_stripe_event_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
