"""add_plan_tier_to_labs

Revision ID: eb9991c11a0b
Revises: w7a8b9c0d1e2
Create Date: 2026-03-06 14:05:24.422922
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9991c11a0b'
down_revision: Union[str, None] = 'w7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('plan_tier', sa.String(length=20), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'plan_tier')
    # ### end Alembic commands ###
